### ISSUE TITLE
sass学习-进阶语法（一）

### ISSUE THREAD

**Issue by lxyc** [lxyc/lxyc-blog#10]
### （一）Sass 的控制命令

> @if
@if 指令是一个 SassScript，它可以根据条件来处理样式块，如果条件为 true 返回一个样式块，反之 false 返回另一个样式块。在 Sass 中除了 @if 之，还可以配合 @else if 和 @else 一起使用

假设要控制一个元素隐藏或显示，我们就可以定义一个混合宏，通过 @if...@else... 来判断传进参数的值来控制 display 的值
```scss
@mixin blockOrHidden($boolean:true) {
@if $boolean {
display: block;
}
@else {
display: none;
}
}

.block {
@include blockOrHidden;
}

.hidden{
@include blockOrHidden(false);
}

// css
.block {
display: block;
}

.hidden {
display: none;
}
```

> @for循环

在 Sass 的 @for 循环中有两种方式:

- `@for $i from <start> through <end>`
- `@for $i from <start> to <end>`

其中：$i 表示变量 / start 表示起始值 / end 表示结束值

这两个的区别是 **关键字 through 表示包括 end 这个数，而 to 则不包括 end 这个数**

```scss
@for $i from 1 through 3 {
.item-#{$i} { width: 2em * $i; }
}

// css
.item-1 { width: 2em; }
.item-2 { width: 4em; }
.item-3 { width: 6em; }

@for $i from 1 to 3 {
.item-#{$i} { width: 2em * $i; }
}

// css
.item-1 { width: 2em; }
.item-2 { width: 4em; }
```
实际中的应用：@for应用在网格系统生成各个格子 class 的代码

```scss
$grid-prefix: span !default;
$grid-width: 60px !default;
$grid-gutter: 20px !default;

%grid {
float: left;
margin-left: $grid-gutter / 2;
margin-right: $grid-gutter / 2;
}
@for $i from 1 through 12 {
.#{$grid-prefix}#{$i}{
width: $grid-width * $i + $grid-gutter * ($i - 1);
@extend %grid;
}
}

// css
.span1, .span2, .span3, .span4, .span5, .span6, .span7, .span8, .span9, .span10, .span11, .span12 {
float: left;
margin-left: 10px;
margin-right: 10px;
}
.span1 { width: 60px; }
.span2 { width: 140px; }
.span3 { width: 220px; }
.span4 { width: 300px; }
.span5 { width: 380px; }
.span6 { width: 460px; }
.span7 { width: 540px; }
.span8 { width: 620px; }
.span9 { width: 700px; }
.span10 { width: 780px; }
.span11 { width: 860px; }
.span12 { width: 940px; }
```

> @while循环

@while 指令也需要 SassScript 表达式（像其他指令一样），并且会生成不同的样式块，直到表达式值为 false 时停止循环。这个和 @for 指令很相似，只要 @while 后面的条件为 true 就会执行

```scss
$types: 4;
$type-width: 20px;

@while $types > 0 {
.while-#{$types} {
width: $type-width + $types;
}
$types: $types - 1;
}

// css
.while-4 { width: 24px; }
.while-3 { width: 23px; }
.while-2 { width: 22px; }
.while-1 { width: 21px; }
```

> @each循环
@each 循环就是去遍历一个列表，然后从列表中取出对应的值

@each 循环指令的形式：`@each $var in <list>`

$var 就是一个变量名，<list> 是一个 SassScript 表达式，他将返回一个列表值。变量 $var 会在列表中做遍历，并且遍历出与 $var 对应的样式块

```scss
$list: adam john wynn mason kuroir;//$list 就是一个列表

@mixin author-images {
@each $author in $list {
.photo-#{$author} {
background: url("/images/avatars/#{$author}.png") no-repeat;
}
}
}

.author-bio {
@include author-images;
}

// css
.author-bio .photo-adam {
background: url("/images/avatars/adam.png") no-repeat; }
.author-bio .photo-john {
background: url("/images/avatars/john.png") no-repeat; }
.author-bio .photo-wynn {
background: url("/images/avatars/wynn.png") no-repeat; }
.author-bio .photo-mason {
background: url("/images/avatars/mason.png") no-repeat; }
.author-bio .photo-kuroir {
background: url("/images/avatars/kuroir.png") no-repeat; }
```

### （二）Sass中的函数 —— 字符串函数

> unquote()函数
unquote() 函数主要是用来删除一个字符串中的引号，如果这个字符串没有带有引号，将返回原始的字符串

unquote() 函数只能删除字符串最前和最后的引号（双引号或单引号），而无法删除字符串中间的引号

如果字符没有带引号，返回的将是字符串本身

```scss
.test1 { content: unquote('Hello Sass!') ; }
.test2 { content: unquote("'Hello Sass!"); }
.test3 { content: unquote("I'm Web Designer"); }
.test4 { content: unquote("'Hello Sass!'"); }
.test5 { content: unquote('"Hello Sass!"'); }
.test6 { content: unquote(Hello Sass); }

// css
.test1 { content: Hello Sass!; }
.test2 { content: 'Hello Sass!; }
.test3 { content: I'm Web Designer; }
.test4 { content: 'Hello Sass!'; }
.test5 { content: "Hello Sass!"; }
.test6 { content: Hello Sass; }
```

> quote() 函数

quote() 函数刚好与 unquote() 函数功能相反，主要用来给字符串添加引号。

如果字符串，自身带有引号会统一换成双引号 ""

使用 quote() 函数只能给字符串增加双引号，而且字符串中间有单引号或者空格时，需要用单引号或双引号括起，否则编译的时候将会报错

同时 quote() 碰到特殊符号，比如： !、?、> 等，除中折号 - 和 下划线_ 都需要使用双引号括起，否则编译器在进行编译的时候同样会报错

```scss
.test1 { content: quote('Hello Sass!'); }
.test2 { content: quote("Hello Sass!"); }
.test3 { content: quote(ImWebDesigner); }
.test4 { content: quote(' '); }

// css
.test1 { content: "Hello Sass!"; }
.test2 { content: "Hello Sass!"; }
.test3 { content: "ImWebDesigner"; }
.test4 { content: ""; }
```

> To-upper-case() 函数
To-upper-case() 函数将字符串小写字母转换成大写字母

```scss
//SCSS
.test {
text: to-upper-case(aaaaa);
text: to-upper-case(aA-aAAA-aaa);
}
//css
.test {
text: AAAAA;
text: AA-AAAA-AAA;
}
```

> To-lower-case() 函数
To-lower-case() 函数 与 To-upper-case() 刚好相反，将字符串转换成小写字母

```scss
//SCSS
.test {
text: to-lower-case(AAAAA);
text: to-lower-case(aA-aAAA-aaa);
}
//CSS
.test {
text: aaaaa;
text: aa-aaaa-aaa;
}
```

### （三）Sass中的函数 —— 数字函数

> percentage() 函数
percentage()函数主要是将一个不带单位的数字转换成百分比形式

如果转换的值是一个带有单位的值，那么在编译的时候会报错误信息

```text
>> percentage(.2)
20%
>> percentage(2px / 10px)
20%
>> percentage(2em / 10em)
20%

>> percentage(2px / 10em)
SyntaxError: $value: 0.2px/em is not a unitless number for `percentage'
```

> random() 函数
round() 函数可以将一个数四舍五入为一个最接近的整数

在round() 函数中可以携带单位的任何数值

```text
>> round(12.3)
12
>> round(12.5)
13
>> round(1.49999)
1
>> round(2.0)
2
>> round(20%)
20%
>> round(2.2%)
2%
>> round(3.9em)
4em
>> round(2.3px)
2px
>> round(2px / 3px)
1
>> round(1px / 3px)
0
>> round(3px / 2em)
2px/em
```

> ceil() 函数
ceil() 函数将一个数转换成最接近于自己的整数，会将一个大于自身的任何小数转换成大于本身 1 的整数。也就是只做入，不做舍的计算

```text
>> ceil(2.0)
2
>> ceil(2.1)
3
>> ceil(2.6)
3
>> ceil(2.3%)
3%
>> ceil(2.3px)
3px
>> ceil(2.5px)
3px
>> ceil(2px / 3px)
1
>> ceil(2% / 3px)
1%/px
>> ceil(1em / 5px)
1em/px
```

> floor() 函数

floor() 函数刚好与 ceil() 函数功能相反，其主要将一个数去除其小数部分，并且不做任何的进位。也就是只做舍，不做入的计算

```text
>> floor(2.1)
2
>> floor(2.5)
2
>> floor(3.5%)
3%
>> floor(10.2px)
10px
>> floor(10.8em)
10em
>> floor(2px / 10px)
0
>> floor(3px / 1em)
3px/em
```

> abs() 函数

abs() 函数会返回一个数的绝对值

```text
>> abs(10)
10
>> abs(-10)
10
>> abs(-10px)
10px
>> abs(-2em)
2em
>> abs(-.5%)
0.5%
>> abs(-1px / 2px)
0.5
```

> min() 函数

min() 函数功能主要是在多个数之中找到最小的一个，这个函数可以设置任意多个参数

min() 函数中同时出现两种不同类型的单位，将会报错误信息

```text
>> min(1,2,1%,3,300%)
1%
>> min(1px,2,3px)
1px
>> min(1em,2em,6em)
1em

>> min(1px,1em)
SyntaxError: Incompatible units: 'em' and 'px'.
```

> max() 函数

max() 函数和 min() 函数一样，不同的是，max() 函数用来获取一系列数中的最大那个值

max() 函数中同时出现两种不同类型的单位，将会报错误信息

```text
>> max(1,5)
5
>> max(1px,5px)
5px

>> max(1,3px,5%,6)
SyntaxError: Incompatible units: '%' and 'px'.
```

> random()函数
random() 函数是用来获取一个随机数 [0, 1)

```text
>> random()
0.03886
>> random()
0.66527
>> random()
0.8125
```
