### ISSUE TITLE
sass学习-进阶语法（四）

### ISSUE THREAD

**Issue by lxyc** [lxyc/lxyc-blog#13]
### Sass的@规则

> @import

Sass 扩展了 CSS 的 @import 规则，让它能够引入 SCSS 和 Sass 文件。 所有引入的 SCSS 和 Sass 文件都会被合并并输出一个单一的 CSS 文件。 另外，被导入的文件中所定义的变量或 mixins 都可以在主文件中使用

@import 根据文件名引入。 默认情况下，它会寻找 Sass 文件并直接引入， 但是，在少数几种情况下，它会被编译成 CSS 的 @import 规则：

- 如果文件的扩展名是 .css
- 如果文件名以 http:// 开头
- 如果文件名是 url()
- 如果 @import 包含了任何媒体查询（media queries）
如果上述情况都没有出现，并且扩展名是 .scss 或 .sass， 该名称的 Sass 或 SCSS 文件就会被引入。 如果没有扩展名， Sass 将试着找出具有 .scss 或 .sass 扩展名的同名文件并将其引入
`@import "foo.scss";` 或 `@import "foo";` 两者都将引入 foo.scss 文件，而

```scss
@import "foo.css";
@import "foo" screen;
@import "http://foo.com/bar";
@import url(foo);

// 编译结果
@import "foo.css";
@import "foo" screen;
@import "http://foo.com/bar";
@import url(foo);
```

也可以通过一个 @import 引入多个文件 `@import "rounded-corners", "text-shadow";`

如果你有一个 SCSS 或 Sass 文件需要引入， 但是你又不希望它被编译为一个 CSS 文件， 这时，你就可以在文件名前面加一个下划线，就能避免被编译。 这将告诉 Sass 不要把它编译成 CSS 文件。 然后，你就可以像往常一样引入这个文件了，而且还可以省略掉文件名前面的下划线

例如，你有一个文件叫做 _colors.scss。 这样就不会生成 _colors.css 文件了， 而且你还可以这样做：
`@import "colors";//不用加下划线` 来引入 _colors.scss 文件

**注意，在同一个目录不能同时存在带下划线和不带下划线的同名文件。 例如， _colors.scss 不能与 colors.scss 并存**

嵌套 @import —— 虽然大部分时间只需在顶层文件使用 @import 就行了， 但是，你还可以把他们包含在 CSS 规则 和 @media 规则中

> @media
Sass 中的 @media 指令和 CSS 的使用规则一样的简单，但它有另外一个功能，可以嵌套在 CSS 规则中。有点类似 JS 的冒泡功能一样，如果在样式中使用 @media 指令，它将冒泡到外面

```scss
.sidebar {
width: 300px;
@media screen and (orientation: landscape) {
width: 500px;
}
}

// 编译结果
.sidebar {
width: 300px;
}
@media screen and (orientation: landscape) {
.sidebar {
width: 500px;
}
}
```

@media 也可以嵌套 @media：

```scss
@media screen {
.sidebar {
@media (orientation: landscape) {
width: 500px;
}
}
}

// 编译结果
@media screen and (orientation: landscape) {
.sidebar {
width: 500px;
}
}
```

在使用 @media 时，还可以使用插件#{}:

```scss
$media: screen;
$feature: -webkit-min-device-pixel-ratio;
$value: 1.5;

@media #{$media} and ($feature: $value) {
.sidebar {
width: 500px;
}
}
// 编译结果
@media screen and (-webkit-min-device-pixel-ratio: 1.5) {
.sidebar {
width: 500px;
}
}
```

> @extend

Sass 中的 @extend 是用来扩展选择器或占位符

```scss
.error {
border: 1px #f00;
background-color: #fdd;
}
.error.intrusion {
background-image: url("/image/hacked.png");
}
.seriousError {
@extend .error;
border-width: 3px;
}

// css
.error, .seriousError {
border: 1px #f00;
background-color: #fdd; }

.error.intrusion, .seriousError.intrusion {
background-image: url("/image/hacked.png"); }

.seriousError {
border-width: 3px; }
```

@extend 不止扩展类选择器，还可以扩展任何选择器，比如 .special.cool, a:hover, 或 a.user[href^=“http://“]

```scss
.hoverlink {
@extend a:hover;
}
a:hover {
text-decoration: underline;
}

// css
a:hover, .hoverlink {
text-decoration: underline; }
```

多个扩展 —— 所设某个样式要继承多个地方的样式，那么可以使用 @extend 来继承多个选择器或占位符的样式

```scss
.error {
border: 1px #f00;
background-color: #fdd;
}
.attention {
font-size: 3em;
background-color: #ff0;
}
.seriousError {
@extend .error;
@extend .attention;
border-width: 3px;
}
```

扩展单一选择器 —— 前面我们知道 %placeholder 不使用@extend显示调用是不会生成任何样式代码。那么在选择器中使用占位符一样

```scss
#context a%extreme {
color: blue;
font-weight: bold;
font-size: 2em;
}

.notice {
@extend %extreme;
}

// css
#context a.notice {
color: blue;
font-weight: bold;
font-size: 2em;
}
```

> @at-root

@at-root 从字面上解释就是跳出根元素。当你选择器嵌套多层之后，想让某个选择器跳出，此时就可以使用 @at-root

```scss
.a {
color: red;

.b {
color: orange;

.c {
color: yellow;

@at-root .d {
color: green;
}
}
}
}

// css
.a {
color: red;
}

.a .b {
color: orange;
}

.a .b .c {
color: yellow;
}

.d {
color: green;
}
```

> @debug

@debug 在 Sass 中是用来调试的，当你的在 Sass 的源码中使用了 @debug 指令之后，Sass 代码在编译出错时，在命令终端会输出你设置的提示 Bug:

```scss
@debug 10em + 12em;

// 输出
Line 1 DEBUG: 22em
```

> @warn

@warn 和 @debug 功能类似，用来帮助我们更好的调试 Sass

```scss
@mixin adjust-location($x, $y) {
@if unitless($x) {
@warn "Assuming #{$x} to be in pixels";
$x: 1px * $x;
}
@if unitless($y) {
@warn "Assuming #{$y} to be in pixels";
$y: 1px * $y;
}
position: relative; left: $x; top: $y;
}

.botton{
@include adjust-location(20px, 30);
}

// 输出
WARNING: Assuming 30 to be in pixels

on line 7 of ./8805/K0Mn/index.scss, in 'adjust-location' from line 16 of ./8805/K0Mn/index.scss
```

> @error
@error 和 @warn、@debug 功能是如出一辙

```scss
@mixin error($x){
@if $x < 10 {
width: $x * 10px;
} @else if $x == 10 {
width: $x;
} @else {
@error "你需要将#{$x}值设置在10以内的数";
}

}

.test {
@include error(15);
}

// 输出
你需要将15值设置在10以内的数 on line 7 at column 5
```
