### ISSUE TITLE
sass学习-初步接触

### ISSUE THREAD

**Issue by lxyc** [lxyc/lxyc-blog#7]
### （一） 什么是 CSS 预处理器？

- 定义：CSS 预处理器用一种专门的编程语言，进行 Web 页面样式设计，然后再编译成正常的 CSS 文件，以供项目使用。CSS 预处理器为 CSS 增加一些编程的特性，无需考虑浏览器的兼容性问题
- 其它 CSS 预处理器语言：`Sass（SCSS）/ LESS / Stylus / Turbine / Swithch CSS / CSS Cacheer / DT CSS`

### （二） 什么是 Sass？

- Sass 是采用 Ruby 语言编写的一款 CSS 预处理语言
- Sass 是一门高于 CSS 的元语言，它能用来清晰地、结构化地描述文件样式，有着比普通 CSS 更加强大的功能
- Sass 能够提供更简洁、更优雅的语法，同时提供多种功能来创建可维护和管理的样式表

### （三） Sass 和 SCSS 有什么区别？

Sass 和 SCSS 其实是同一种东西，我们平时都称之为 Sass，两者之间不同之处有以下两点：

- 文件扩展名不同，Sass 是以".sass"后缀为扩展名，而 SCSS 是以".scss"后缀为扩展名
- 语法书写方式不同，Sass 是以严格的缩进式语法规则来书写，不带大括号和分号，而 SCSS 的语法书写和我们的 CSS 语法书写方式非常类似
```scss
// Sass语法
$font-stack: Helvetica, sans-serif //定义变量
$primary-color: ##333 //定义变量

body
font: 100% $font-stack
color: $primary-color

// SCSS语法
$font-stack: Helvetica, sans-serif;
$primary-color: ##333;

body {
font: 100% $font-stack;
color: $primary-color;
}

// 编译出来的CSS
body {
font: 100% Helvetica, sans-serif;
color: ##333;
}
```

### （四） sass 如何编译

三种编译方式： 命令编译 GUI工具编译 自动化编译

> 命令编译
命令编译是指使用你电脑中的命令终端，通过输入 Sass 指令来编译 Sass。这种编译方式是最直接也是最简单的一种方式。因为只需要在你的命令终端输入：

单文件编译： `sass <要编译的Sass文件路径>/style.scss:<要输出CSS文件路径>/style.css`
多文件编译： `sass sass/:css/` —— 将项目中 sass 文件夹中所有 .scss / .sass 文件编译成 .css 文件，并且将这些 CSS 文件都放在项目中 css 文件夹中

**上面的命令，只能一次性编译**

==> 命令编译中比较推崇的方式：在编译 Sass 时，开启"watch"功能，这样只要你的代码进行任保修改，都能自动监测到代码的变化，并且给你直接编译出来

`sass --watch <要编译的Sass文件路径>/style.scss:<要输出CSS文件路径>/style.css`

> GUI 界面工具编译
Koala（推荐） (http://koala-app.com/)
Compass.app（http://compass.kkbox.com/）
Scout（http://mhs.github.io/scout-app/）
CodeKit（推荐）（https://incident57.com/codekit/index.html）
Prepros（https://prepros.io/）

> 自动化构建工具：gulp / grunt / webpack
### （五） 不同样式风格的输出方法
四种样式风格： 嵌套输出方式 nested / 展开输出方式 expanded / 紧凑输出方式 compact / 压缩输出方式 compressed

```scss
nav {
ul {
margin: 0;
padding: 0;
list-style: none;
}

li { display: inline-block; }

a {
display: block;
padding: 6px 12px;
text-decoration: none;
}
}
```

> 嵌套输出方式 nested （默认输出方式）

编译的时候带上参数"--style nested": `sass --watch test.scss:test.css --style nested`

```css
nav ul {
margin: 0;
padding: 0;
list-style: none; }
nav li {
display: inline-block; }
nav a {
display: block;
padding: 6px 12px;
text-decoration: none; }
```

> 展开输出方式 expanded

在编译的时候带上参数"--style expanded": `sass --watch test.scss:test.css --style expanded`

```css
nav ul {
margin: 0;
padding: 0;
list-style: none;
}
nav li {
display: inline-block;
}
nav a {
display: block;
padding: 6px 12px;
text-decoration: none;
}
```

> 紧凑输出方式 compact

在编译的时候带上参数"--style compact": `sass --watch test.scss:test.css --style compact`

```css
nav ul { margin: 0; padding: 0; list-style: none; }
nav li { display: inline-block; }
nav a { display: block; padding: 6px 12px; text-decoration: none; }
```

> 压缩输出方式 compressed

在编译的时候带上参数"--style compressed": `sass --watch test.scss:test.css --style compressed`

```css
nav ul{margin:0;padding:0;list-style:none}nav li{display:inline-block}nav a{display:block;padding:6px 12px;text-decoration:none}
```
