### ISSUE TITLE
sass学习-基本语法

### ISSUE THREAD

**Issue by lxyc** [lxyc/lxyc-blog#8]
### （一）变量

> 变量声明

  用法：`$width: 300px;` 
  组成：声明变量的符号"$" 变量名称: 赋予变量的值 (!default)

```scss
  // 如果值后面加上 !default 则表示默认值
  $brand-primary : darken(#428bca, 6.5%) !default; // #337ab7
  $btn-primary-color : #fff !default;
  $btn-primary-bg : $brand-primary !default;
  $btn-primary-border : darken($btn-primary-bg, 5%) !default;
```

- **什么时候声明变量？**

  只有满足所有下述标准时方可创建新变量：
    + 该值至少重复出现了两次；
    + 该值至少可能会被更新一次；
    + 该值所有的表现都与变量有关（非巧合）。

- **普通变量语默认变量**
  
  **普通变量：** 定义之后可以在全局范围内使用

```scss
  $fontSize: 12px;
  body{
      font-size:$fontSize;
  }

  // output
  body{
      font-size:12px;
  }
```

  **默认变量：** sass 的默认变量仅需要在值后面加上 !default 即可

```scss
  $baseLineHeight:1.5 !default;
  body{
      line-height: $baseLineHeight; 
  }

  // output
  body{
      line-height:1.5;
  }
```

  **区别：** sass 的默认变量一般是用来设置默认值，然后根据需求来覆盖的，覆盖的方式也很简单，只需要在默认变量之前重新声明下变量即可

```scss
  $baseLineHeight: 2;
  $baseLineHeight: 1.5 !default;
  body{
      line-height: $baseLineHeight; 
  }

  // output
  body{
      line-height: 2;
  }
```

  **默认变量的价值在进行组件化开发的时候会非常有用**

> 变量的调用

```scss
  .btn-primary {
     background-color: $btn-primary-bg;
     color: $btn-primary-color;
     border: 1px solid $btn-primary-border;
  }
```

> 局部变量和全局变量
  
  在选择器、函数、混合宏...的外面定义的变量为全局变量，其他的为局部变量

```scss
  $color: orange !default;//定义全局变量
  .block {
    color: $color;//调用全局变量
  }
  em {
    $color: red;//定义局部变量
    a {
      color: $color;//调用局部变量
    }
  }
  span {
    color: $color;//调用全局变量
  }

  // output
  .block {
    color: orange;
  }
  em a {
    color: red;
  }
  span {
    color: orange;
  }
```

### （二）嵌套
  
  Sass 的嵌套分为三种：选择器嵌套 / 属性嵌套 / 伪类嵌套

> 选择器嵌套

  **注意：** 嵌套的层级越深，编译出来的 CSS 代码的选择器层级将越深，对性能影响越大

```scss
  // css
  nav a {
    color:red;
  }

  header nav a {
    color:green;
  }

  // scss
  nav {
    a {
      color: red;

      header & {
        color:green;
      }
    }  
  }

```

> 属性嵌套
  
  适用于一些属性前缀相同，只是后缀不一样，比如：border-top/border-right，与这个类似的还有 margin、padding、font 等属性

```scss
  // css
  .box {
      border-top: 1px solid red;
      border-bottom: 1px solid green;
  }

  // scss
  .box {
    border: {
     top: 1px solid red;
     bottom: 1px solid green;
    }
  }
```

> 伪类嵌套

  伪类嵌套和属性嵌套非常类似，只不过他需要借助`&`符号一起配合使用

```scss
  // css
  clearfix:before, .clearfix:after {
    content: "";
    display: table;
  }
  .clearfix:after {
    clear: both;
    overflow: hidden;
  }

  // scss
  .clearfix{
    &:before,
    &:after {
      content:"";
      display: table;
    }
    &:after {
      clear:both;
      overflow: hidden;
    }
  }
```

### （三）混合宏

> 声明混合宏

  - **不带参数混合宏**
  
  在 Sass 中，使用"@mixin"来声明一个混合宏。如：

```scss
  @mixin border-radius{
      -webkit-border-radius: 5px;
      border-radius: 5px;
  }
```

  其中 @mixin 是用来声明混合宏的关键词，有点类似 CSS 中的 @media、@font-face 一样。border-radius 是混合宏的名称。大括号里面是复用的样式代码。

  - **带参数混合宏**

  除了声明一个不带参数的混合宏之外，还可以在定义混合宏时带有参数，如：

```scss
  @mixin border-radius($radius:5px){
      -webkit-border-radius: $radius;
      border-radius: $radius;
  }
```

  - **复杂的混合宏**

  在大括号里面写上带有逻辑关系，如：

```scss
  @mixin box-shadow($shadow...) {
    @if length($shadow) >= 1 {
      @include prefixer(box-shadow, $shadow);
    } @else{
      $shadow:0 0 4px rgba(0,0,0,.3);
      @include prefixer(box-shadow, $shadow);
    }
  }
```

  这个 box-shadow 的混合宏，带有多个参数，这个时候可以使用" … "来替代。简单的解释一下，当 $shadow 的参数数量值大于或等于" 1 "时，表示有多个阴影值，反之调用默认的参数值" 0 0 4px rgba(0,0,0,.3) "

> 调用混合宏

  在 Sass 中通过 @mixin 关键词声明了一个混合宏，那么在实际调用中，其匹配了一个关键词"@include"来调用声明好的混合宏

```scss
  // 定义
  @mixin border-radius{
      -webkit-border-radius: 3px;
      border-radius: 3px;
  }

  // 调用
  button {
      @include border-radius;
  }

  // 编译结果
  button {
      -webkit-border-radius: 3px;
      border-radius: 3px;
  }
```

> 混合宏的参数

  - 传一个不带值的参数

```scss
  // 定义
  @mixin border-radius($radius){
    -webkit-border-radius: $radius;
    border-radius: $radius;
  }

  // 调用
  .btn {
    @include border-radius(3px);
  }
  
  // 编译结果
  .btn {
    -webkit-border-radius: 3px;
    border-radius: 3px;
  }
```

  - 传一个带值的参数(含默认值)

```scss
  // 定义
  @mixin border-radius($radius: 3px){
    -webkit-border-radius: $radius;
    border-radius: $radius;
  }

  // 调用（一）
  .btn {
    @include border-radius;
  }

  // 编译结果（一）
  .btn {
    -webkit-border-radius: 3px;
    border-radius: 3px;
  }

  // 调用（二）
  .btn {
    @include border-radius(50%);
  }

  // 编译结果（二）
  .btn {
    -webkit-border-radius: 50%;
    border-radius: 50%;
  }
```

  - 传多个参数
  
```scss
  // 定义
  @mixin center($width,$height){
    width: $width;
    height: $height;
    position: absolute;
    top: 50%;
    left: 50%;
    margin-top: -($height) / 2;
    margin-left: -($width) / 2;
  }

  // 调用
  .box-center {
    @include center(500px,300px);
  }
```

  有一个特别的参数"…"。当混合宏传的参数过多之时，可以使用参数来替代

```scss
  // 定义
  @mixin box-shadow($shadows...){
    @if length($shadows) >= 1 {
      -webkit-box-shadow: $shadows;
      box-shadow: $shadows;
    } @else {
      $shadows: 0 0 2px rgba(#000,.25);
      -webkit-box-shadow: $shadow;
      box-shadow: $shadow;
    }
  }

  // 调用
  .box {
    @include box-shadow(0 0 1px rgba(#000,.5),0 0 2px rgba(#000,.2));
  }
```

### （四）扩展/继承

  在 Sass 中是通过关键词 "@extend"来继承已存在的类样式块，从而实现代码的继承

```scss
  //SCSS
  .btn {
    border: 1px solid #ccc;
    padding: 6px 10px;
    font-size: 14px;
  }

  .btn-primary {
    background-color: #f36;
    color: #fff;
    @extend .btn;
  }

  .btn-second {
    background-color: orange;
    color: #fff;
    @extend .btn;
  }
```

### （五）占位符 %placeholder

  Sass 中的占位符 %placeholder 功能是一个很强大，很实用的一个功能，这也是我非常喜欢的功能。他可以取代以前 CSS 中的基类造成的代码冗余的情形。因为 %placeholder 声明的代码，如果不被 @extend 调用的话，不会产生任何代码

```scss
  // 这段代码没有被 @extend 调用，他并没有产生任何代码块
  %mt5 {
    margin-top: 5px;
  }
  %pt5 {
    padding-top: 5px;
  }

  // 调用
  .btn {
    @extend %mt5;
    @extend %pt5;
  }

  .block {
    @extend %mt5;

    span {
      @extend %pt5;
    }
  }

  // 编译出来的代码会将相同的代码合并在一起
  .btn, .block {
    margin-top: 5px;
  }

  .btn, .block span {
    padding-top: 5px;
  }
```

### （六）混合宏 VS 继承 VS 占位符

  **什么时候用混合宏，什么时候用继承，什么时候使用占位符？**

  > Sass 中的混合宏使用
  
```scss
  //SCSS中混合宏使用
  @mixin mt($var){
    margin-top: $var;  
  }

  .block {
    @include mt(5px);
    span {
      display:block;
      @include mt(5px);
    }
  }

  .header {
    color: orange;
    @include mt(5px);
    span{
      display:block;
      @include mt(5px);
    }
  }

  // css
  .block {
    margin-top: 5px; 
  }
  .block span {
    display: block;
    margin-top: 5px; 
  }
  .header {
    color: orange;
    margin-top: 5px; 
  }
  .header span {
    display: block;
    margin-top: 5px; 
  }
```

  **总结：** 编译出来的 CSS 清晰告诉了大家，他不会自动合并相同的样式代码，如果在样式文件中调用同一个混合宏，会产生多个对应的样式代码，造成代码的冗余，这也是 CSSer 无法忍受的一件事情。不过他并不是一无事处，他可以传参数。

  **个人建议：** 如果你的代码块中涉及到变量，建议使用混合宏来创建相同的代码块。
  
  > Sass 中继承

```scss
  //SCSS 继承的运用
  .mt{
    margin-top: 5px;  
  }

  .block {
    @extend .mt;

    span {
      display:block;
      @extend .mt;
    }
  }

  .header {
    color: orange;
    @extend .mt;

    span{
      display:block;
      @extend .mt;
    }
  }

  // css
  .mt, .block, .block span, .header, .header span {
    margin-top: 5px; 
  }
  .block span {
    display: block; 
  }
  .header {
    color: orange; 
  }
  .header span {
    display: block; 
  }
```
  
  **总结：** 使用继承后，编译出来的 CSS 会将使用继承的代码块合并到一起，通过组合选择器的方式向大家展现，比如 .mt, .block, .block span, .header, .header span。这样编译出来的代码相对于混合宏来说要干净的多，也是 CSSer 期望看到。但是他不能传变量参数。

  **个人建议：** 如果你的代码块不需要专任何变量参数，而且有一个基类已在文件中存在，那么建议使用 Sass 的继承

  > 占位符

```scss
  //SCSS中占位符的使用
  %mt{
    margin-top: 5px;  
  }

  .block {
    @extend %mt;

    span {
      display:block;
      @extend %mt;
    }
  }

  .header {
    color: orange;
    @extend %mt;

    span{
      display:block;
      @extend %mt;
    }
  }

  // css
  .mt, .block, .block span, .header, .header span {
    margin-top: 5px; 
  }
  .block span {
    display: block; 
  }
  .header {
    color: orange; 
  }
  .header span {
    display: block; 
  }
```
  
  **总结：** 编译出来的 CSS 代码和使用继承基本上是相同，只是不会在代码中生成占位符 mt 的选择器。那么占位符和继承的主要区别的，"占位符是独立定义，不调用的时候是不会在 CSS 中产生任何代码；继承是首先有一个基类存在，不管调用与不调用，基类的样式都将会出现在编译出来的 CSS 代码中

### （七）插值#{}

  - 构建选择器

```scss
  @mixin generate-sizes($class, $small, $medium, $big) {
      .#{$class}-small { font-size: $small; }
      .#{$class}-medium { font-size: $medium; }
      .#{$class}-big { font-size: $big; }
  }
  @include generate-sizes("header-text", 12px, 20px, 40px);

  // css
  .header-text-small { font-size: 12px; }
  .header-text-medium { font-size: 20px; }
  .header-text-big { font-size: 40px; }
```

  - 搭配extend使用
```scss
  %updated-status {
      margin-top: 20px;
      background: #F00;
  }
  .selected-status {
      font-weight: bold;
  }
  $flag: "status";
  .navigation {
      @extend %updated-#{$flag};
      @extend .selected-#{$flag};
  }

  // css
  .navigation {
      margin-top: 20px;
      background: #F00;
  }
  .selected-status, .navigation {
      font-weight: bold;
  }
```

  - #{} 错误用法
```scss
  // 错误用法一
  $margin-small: 12px;
  @mixin set-value($size) {
      margin-top: $margin-#{$size};
  }

  // 错误用法二 （不能在 mixin 中调用）
  @mixin updated-status {
      margin-top: 20px;
      background: #F00;
  }
  $flag: "status";
  .navigation {
      @include updated-#{$flag};
  }
```
